# Generated by Django 4.2.20 on 2025-04-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_alter_task_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', '低'), ('Medium', '中'), ('High', '高')], default='Medium', max_length=10),
        ),
    ]
