# Generated by Django 4.2.20 on 2025-04-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0007_alter_task_priority_taskcategory_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('工作', '工作'), ('学习', '学习'), ('生活', '生活'), ('娱乐', '娱乐')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='TaskCategory',
        ),
    ]
