# Generated by Django 4.2.20 on 2025-04-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0010_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', '普通'), ('Medium', '紧急'), ('High', '非常紧急')], default='Low', max_length=10),
        ),
    ]
