# Generated by Django 4.2.19 on 2025-04-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0011_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('工作', '工作'), ('学习', '学习'), ('生活', '生活'), ('娱乐', '娱乐')], default='工作', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', '普通'), ('Medium', '紧急'), ('High', '非常紧急')], default='Low', max_length=10),
        ),
    ]
